-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


ALTER TABLE IF EXISTS public."Comentarios" DROP CONSTRAINT IF EXISTS "FK_Comentarios_Peliculas_PeliculaId";

ALTER TABLE IF EXISTS public."PeliculasActores" DROP CONSTRAINT IF EXISTS "FK_PeliculasActores_Actores_ActorId";

ALTER TABLE IF EXISTS public."PeliculasActores" DROP CONSTRAINT IF EXISTS "FK_PeliculasActores_Peliculas_PeliculaId";



DROP TABLE IF EXISTS public."Actores";

CREATE TABLE IF NOT EXISTS public."Actores"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Nombre" character varying(150) COLLATE pg_catalog."default" NOT NULL,
    "Fortuna" numeric(18, 2) NOT NULL,
    "FechaNacimiento" date NOT NULL,
    CONSTRAINT "PK_Actores" PRIMARY KEY ("Id")
);

DROP TABLE IF EXISTS public."Comentarios";

CREATE TABLE IF NOT EXISTS public."Comentarios"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Contenido" character varying(500) COLLATE pg_catalog."default",
    "Recomendar" boolean NOT NULL,
    "PeliculaId" integer NOT NULL DEFAULT 0,
    CONSTRAINT "PK_Comentarios" PRIMARY KEY ("Id")
);

DROP TABLE IF EXISTS public."Generos";

CREATE TABLE IF NOT EXISTS public."Generos"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Nombre" character varying(150) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PK_Generos" PRIMARY KEY ("Id")
);

DROP TABLE IF EXISTS public."Peliculas";

CREATE TABLE IF NOT EXISTS public."Peliculas"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Titulo" character varying(150) COLLATE pg_catalog."default" NOT NULL,
    "EnCines" boolean NOT NULL,
    "FechaEstreno" date NOT NULL,
    CONSTRAINT "PK_Peliculas" PRIMARY KEY ("Id")
);

DROP TABLE IF EXISTS public."PeliculasActores";

CREATE TABLE IF NOT EXISTS public."PeliculasActores"
(
    "PeliculaId" integer NOT NULL,
    "ActorId" integer NOT NULL,
    "Personaje" character varying(150) COLLATE pg_catalog."default" NOT NULL,
    "Orden" integer NOT NULL,
    CONSTRAINT "PK_PeliculasActores" PRIMARY KEY ("PeliculaId", "ActorId")
);

DROP TABLE IF EXISTS public."__EFMigrationsHistory";

CREATE TABLE IF NOT EXISTS public."__EFMigrationsHistory"
(
    "MigrationId" character varying(150) COLLATE pg_catalog."default" NOT NULL,
    "ProductVersion" character varying(32) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

ALTER TABLE IF EXISTS public."Comentarios"
    ADD CONSTRAINT "FK_Comentarios_Peliculas_PeliculaId" FOREIGN KEY ("PeliculaId")
    REFERENCES public."Peliculas" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_Comentarios_PeliculaId"
    ON public."Comentarios"("PeliculaId");


ALTER TABLE IF EXISTS public."PeliculasActores"
    ADD CONSTRAINT "FK_PeliculasActores_Actores_ActorId" FOREIGN KEY ("ActorId")
    REFERENCES public."Actores" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_PeliculasActores_ActorId"
    ON public."PeliculasActores"("ActorId");


ALTER TABLE IF EXISTS public."PeliculasActores"
    ADD CONSTRAINT "FK_PeliculasActores_Peliculas_PeliculaId" FOREIGN KEY ("PeliculaId")
    REFERENCES public."Peliculas" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

END;